remote_theme: yaoeh/dspg22_minimal-mistakes

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

title: "Summer 2022"
logo: "https://raw.githubusercontent.com/yaoeh/dspg22_minimal-mistakes/master/assets/img/logo-white.png"
repository: "yaoeh/dspg22_product-innovation"
